### ISSUE TITLE
Limitation of plugin usage with `editing` mode only

### ISSUE THREAD

**Issue by pidgeon777** [oflisback/obsidian-bridge.nvim#11]
From the README:

```markdown
Now scrolling a note in neovim should also result in scrolling in Obsidian. Note however that this only works if the note is in editing mode in Obsidian. Any suggestions on how to make it work also in view mode would be very appreciated, until then make sure that notes are opened in editing mode by default via the Obsidian setting Editor -> Default view for new tabs -> Editing view.
```

I think it would be great to be able to scroll in view mode as well.

As a workaround, maybe it would be possible to something as follows:

1. Scroll in edit mode
2. Switch to view mode

So it would be necessary to have a command to automatically switch to view mode with curl method.

Edit mode would instead be activated when the scroll event is triggered.

Do you think something like this would be feasible?

**Comment by oflisback** [comment]
Sorry for the super slow response on this, yes that would be interesting to try. There is a command available in upstream [obsidian-local-rest-api](https://github.com/coddingtonbear/obsidian-local-rest-api) that looks promising:

```
    {
      "id": "markdown:toggle-preview",
      "name": "Toggle reading view"
    }
```

Please let me know if you try it out, otherwise I hope to do it myself in the coming weeks.

**Comment by oflisback** [comment]
Without a way to specifically set reading or editing mode or there's a way to read the current mode, I don't think this is possible.
