### ISSUE TITLE
Add an instruction to readme to set the API key in init.lua

### ISSUE THREAD

**Issue by YousufSSyed** [oflisback/obsidian-bridge.nvim#22]
The environment variable API key can be set in init.lua like so:

```lua
vim.env.OBSIDIAN_REST_API_KEY = "your api key, without the quotes"
```

**Comment by oflisback** [comment]
I don't think we should encourage anyone to put their API key in their neovim config since it often ends up in their public dotfiles repo. A better alternative to using an env variable altogether would be to allow for an executable to provide the value, that's something I might add.

But thanks for the suggestion and thanks for taking the time to suggest an improvement.
